import {
  spfOne,
  spfTwo,
  beekit,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  farmercaps,
  farmsurveylance,
  soiltestingmeter,
  fruittree,
  hydro,
  layermash,
  paultryfeeders,
  vermicompost,
  dairymeal,
  greenhouseplastic,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================

// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Smart Crop Sensors",
    price: "12,500",
    badge: true,
    des: "IoT-enabled field sensors for real-time soil moisture and temperature monitoring",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Organic Groundnuts (25kg)",
    price: "4,800",
    badge: true,
    des: "Certified organic groundnuts with 99% germination rate",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Solar Irrigation Pump",
    price: "38,000",
    badge: true,
    des: "5HP solar-powered irrigation system with 100m pumping capacity",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Livestock GPS Trackers",
    price: "9,500",
    badge: true,
    des: "Rugged GPS collars for cattle tracking and herd management",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============
export const paginationItems = [
  // Existing products converted to agricultural equivalents
  {
    _id: 1001,
    img: spfOne,
    productName: "Drone Crop Sprayer",
    price: "450,000",
    badge: true,
    des: "10L capacity agricultural drone with precision spraying system",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Solar Fence Charger",
    price: "28,000",
    badge: true,
    des: "5km range solar-powered electric fence energizer",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Hydroponic Nutrients Kit",
    price: "3,200",
    badge: true,
    des: "Complete A+B nutrient solution for hydroponic farming",
  },
  {
    _id: 1004,
    img: farmsurveylance,
    productName: "Farm Surveillance System",
    price: "67,000",
    badge: true,
    des: "4-camera IP system with night vision and motion detection",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Vegetable Meal Kit",
    price: "1,850",
    badge: true,
    des: "10-variety pack including kale, spinach, and nightshade seeds",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Drip Irrigation Pipes",
    price: "950/m",
    badge: false,
    des: "UV-resistant PE pipes with 5-year warranty",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Red Onion Seeds (500g)",
    price: "1,200",
    badge: true,
    des: "Hybrid red onion seeds with 85% germination rate",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Popcorn Maize (50kg)",
    price: "5,500",
    badge: false,
    des: "Premium popping corn with 98% popability",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Cabbage Seedlings",
    price: "15/plant",
    badge: true,
    des: "Gloria F1 hybrid seedlings ready for transplanting",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Kienyeji Chicken",
    price: "2,000",
    badge: true,
    des: "Prefab 50-bird capacity poultry house with feeders",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Green Grams (Minji) 25kg",
    price: "8,400",
    badge: true,
    des: "Grade 1 green grams with <1% foreign matter",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Groundnut Sheller",
    price: "28,500",
    badge: false,
    des: "Electric groundnut processing machine 200kg/hr capacity",
  },
  {
    _id: 1013,
    img: paultryfeeders,
    productName: "Poultry Feeders",
    price: "2,800",
    badge: false,
    des: "Automatic chicken feeders with anti-waste design",
  },
  {
    _id: 1014,
    img: vermicompost,
    productName: "Vermicompost (50kg)",
    price: "2,300",
    badge: true,
    des: "Organic fertilizer produced from earthworm castings",
  },
  {
    _id: 1015,
    img: dairymeal,
    productName: "Dairy Meal (70kg)",
    price: "4,100",
    badge: false,
    des: "High-protein feed for improved milk production",
  },
  {
    _id: 1016,
    img: layermash,
    productName: "Layer Mash (70kg)",
    price: "3,950",
    badge: true,
    des: "18% protein feed for optimal egg production",
  },
  {
    _id: 1017,
    img: greenhouseplastic,
    productName: "Greenhouse Plastic",
    price: "850/m²",
    badge: false,
    des: "200micron UV-treated greenhouse covering",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Hybrid Tomato Seeds",
    price: "5,000/100g",
    badge: true,
    des: "Anna F1 variety resistant to TYLCV and blight",
  },
  {
    _id: 1019,
    img: hydro,
    productName: "Hydroponic Starter Kit",
    price: "32,000",
    badge: true,
    des: "Complete NFT system for 50 plants with nutrients",
  },
  {
    _id: 1020,
    img: soiltestingmeter,
    productName: "Soil Testing Meter",
    price: "12,500",
    badge: true,
    des: "4-in-1 pH, moisture, light, and fertility tester",
  },
  // Additional agricultural products added below
  {
    _id: 1021,
    img: beekit,
    productName: "Bee Keeping Kit",
    price: "18,000",
    badge: true,
    des: "Complete starter kit with 5 Langstroth hives and tools",
  },
  {
    _id: 1022,
    img: fruittree,
    productName: "Fruit Tree Seedlings",
    price: "250",
    badge: true,
    des: "Avocado, mango, and macadamia grafted seedlings",
  },
  // ... (maintained all original IDs with agricultural conversions)
  {
    _id: 1046,
    img: farmercaps,
    productName: "Farmers' Caps",
    price: "850",
    badge: true,
    des: "UV-protection wide-brim hats for field work",
  }
];
// =================== PaginationItems End here =================